#!/bin/bash
## by John Modica 
### @CybernetiX S3C


HEIGHT=15
WIDTH=40
CHOICE_HEIGHT=10
BACKTITLE="Kali Linux DB Update Menu"
TITLE="Kali Desktop Enviroment & Window Managers"
MENU="Choose one of the following options:"

OPTIONS1=(1 "Kali Core"
         2 "Kali Enlightenment {WM}"
         3 "Kali Gnome {DE}"
         4 "Kali i3 {WM}"
         5 "Kali KDE {DE}"
         6 "Kali LXDE {WM}"
         7 "Kali MATE {DE}" 
         8 "Kali XFCE {WM}"
         9 "Main Menu"
         10 "Quit")

CHOICE=$(dialog --clear \
                --backtitle "$BACKTITLE" \
                --title "$TITLE" \
                --menu "$MENU" \
                $HEIGHT $WIDTH $CHOICE_HEIGHT \
                "${OPTIONS1[@]}" \
                2>&1 >/dev/tty)

clear

case $CHOICE in
        1)  
            echo "Installing Kali Core Files.";
            sleep 2
            sudo apt install kali-desktop-core;
            sleep 1
            KDesk;
            ;;
        2)  
            echo "Installing Kali Enlightenment.";
            sleep 2
            sudo apt install kali-desktop-e17;
            sleep 1
            KDesk;
            ;;
        3)
            echo "Installing Kali Gnome.";
            sleep 2
            sudo apt install kali-desktop-gnome;
            sleep 1
            KDesk;
            ;;
        4)
            echo "Installing Kali i3."
            sleep 2
            sudo apt install kali-desktop-i3;
            sleep 1
            KDesk;
            ;;
        5) 
            echo "Installing Kali KDE.";
            sleep 2
            sudo apt install kali-desktop-kde;
            sleep 1
            KDesk
            ;;
        6)
            echo "Installing Kali LXDE.";
            sleep 2
            sudo apt install kali-desktop-lxde;
            sleep 1
            KDesk
            ;;
        7)
            echo "Installing Kali Mate.";
            sleep 2
            sudo apt install kali-desktop-mate;
            sleep 1
            KDesk
            ;;
        8)
            echo "Installing Kali XFCE.";
            sleep 2
            sudo apt install kali-desktop-xfce;
            sleep 1
            KDesk
            ;;

        9)
            echo "Main Menu"
            sleep 1
            kali-db
            ;;
        10)  
            echo "Done"
esac

