#!/bin/bash
## by John Modica 
### @CybernetiX S3C


HEIGHT=15
WIDTH=40
CHOICE_HEIGHT=10
BACKTITLE="Kali Linux DB Update Menu"
TITLE="Kali System Metapackages"
MENU="Choose one of the following options:"

OPTIONS1=(1 "Kali Core"
         2 "Kali Default"
         3 "Kali Light"
         4 "Kali Arm"
         5 "Kali Nethunter"
         6 "Main Menu"
         7 "Quit")

CHOICE=$(dialog --clear \
                --backtitle "$BACKTITLE" \
                --title "$TITLE" \
                --menu "$MENU" \
                $HEIGHT $WIDTH $CHOICE_HEIGHT \
                "${OPTIONS1[@]}" \
                2>&1 >/dev/tty)

clear

case $CHOICE in
        1)  
            echo "Installing Kali Core. This is the Kali Linux System Base Files.";
            sleep 2
            sudo apt install kali-linux-core;
            sleep 1
            KSystem;
            ;;
        2)  
            echo "Installing Kali Default. This package is the (amd64/i386) images.";
            sleep 2
            sudo apt install kali-linux-default;
            sleep 1
            KSystem;
            ;;
        3)
            echo "Installing Kali Light. This package contains the Core, firefox, and openssh-server.";
            sleep 2
            sudo apt install kali-linux-light;
            sleep 1
            KSystem;
            ;;
        4)
            echo "Installing Kali Arm. This package has tools suitable for ARM devices."
            sleep 2
            sudo apt install kali-linux-arm;
            sleep 1
            KSystem;
            ;;
        5) 
            echo "Installing Kali Nethunter. This package contains tools for Nethunter.";
            sleep 2
            sudo apt install kali-linux-nethunter;
            sleep 1
            KSystem
            ;;
        6)
            echo "Main Menu"
            sleep 1
            kali-db
            ;;
        7)  
            echo "Done"
esac


