Document: kali-db
Title: Debian kali-db Manual
Author: <insert document author here>
Abstract: This manual describes what kali-db is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/kali-db/kali-db.sgml.gz

Format: postscript
Files: /usr/share/doc/kali-db/kali-db.ps.gz

Format: text
Files: /usr/share/doc/kali-db/kali-db.text.gz

Format: HTML
Index: /usr/share/doc/kali-db/html/index.html
Files: /usr/share/doc/kali-db/html/*.html
